<a href="https://colab.research.google.com/github/Melany1523/IAWorks/blob/main/Numpy_Excercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

aux = np.array([1,2,4,5])
print(aux)
print(aux.shape)
print ("-------------------------------------")
aux = np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print ("-------------------------------------")
tmp = np.zeros([4,4])
print (tmp)
print ("-------------------------------------")
tmp = np.full([4,4],5)
print (tmp)
print ("-------------------------------------")
tmp = np.eye(4,4)
print (tmp)
print ("-------------------------------------")
tmp = np.ones([4,4])
print (tmp)
print (tmp.shape)
print ("-------------------------------------")
tmp = 10*np.random.random([3,3])
print (tmp)

[1 2 4 5]
(4,)
-------------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
-------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
-------------------------------------
[[0.36386617 4.1066417  4.83103559]
 [2.33676968 3.59224053 9.82754987]
 [6.08354871 4.02120863 9.19429069]]


In [2]:
tmp = 10*np.random.random([3,3])
print (tmp)

[[8.11591939 3.17801725 5.34499183]
 [8.9150112  4.33700795 4.82241559]
 [1.83067729 4.67987557 8.2942277 ]]


In [3]:
print (tmp[:2,:2])

[[8.11591939 3.17801725]
 [8.9150112  4.33700795]]


In [4]:
print (tmp[:2,1:3])

[[3.17801725 5.34499183]
 [4.33700795 4.82241559]]


In [5]:
print (tmp [2,2])

8.294227697378314


Filtrar valores con mask

In [6]:
mask = tmp>5
print (tmp[mask])

[8.11591939 5.34499183 8.9150112  8.2942277 ]


In [7]:
mask = (tmp>=2) & (tmp<=4)
print (tmp[mask])

[3.17801725]


In [8]:
tmp = np.random.randint(0,10,[4,4])
print (tmp)

[[3 5 0 0]
 [8 6 4 4]
 [5 7 1 4]
 [8 2 3 7]]


extraer los numeros pares

In [9]:
nrosEnteros = np.random.randint(0, 10, size=(4, 4))
print(nrosEnteros)


print('---------------------------')
nrosEnteros = nrosEnteros[nrosEnteros % 2 == 0]
print(nrosEnteros)


[[1 7 6 3]
 [3 3 8 2]
 [0 1 1 5]
 [8 1 8 1]]
---------------------------
[6 8 2 0 8 8]
