<a href="https://colab.research.google.com/github/Melany1523/IAWorks/blob/main/Numpy_Excercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy.random import MT19937
import numpy as np
print ("Matriz 1")
m1 = np.random.randint(1,11,[3,4])
print (m1)
print (m1.shape)
print ("Matriz 2")
m2 = np.random.randint(1,11,[3,4])
print (m2)
print (m2.shape)
print ("Suma de matrices")
print (m1 + m2)
print ("Resta de matrices")
print (m1 - m2)
print ("Multiplicacion de matrices")
print (m1 * m2)

Matriz 1
[[ 1  4  2  8]
 [ 4 10  7  2]
 [ 1  3 10  2]]
(3, 4)
Matriz 2
[[ 7  1  3  5]
 [10  7  1 10]
 [ 2  9  2  5]]
(3, 4)
Suma de matrices
[[ 8  5  5 13]
 [14 17  8 12]
 [ 3 12 12  7]]
Resta de matrices
[[-6  3 -1  3]
 [-6  3  6 -8]
 [-1 -6  8 -3]]
Multiplicacion de matrices
[[ 7  4  6 40]
 [40 70  7 20]
 [ 2 27 20 10]]


In [2]:
print ("Suma de matrices")
print (np.add(m1,m2))
print ("Resta de matrices")
print (np.subtract(m1,m2))
print ("Multiplicacion de matrices")
print (np.multiply(m1,m2))
print ("Division de matrices")
print (np.divide(m1,m2))

Suma de matrices
[[ 8  5  5 13]
 [14 17  8 12]
 [ 3 12 12  7]]
Resta de matrices
[[-6  3 -1  3]
 [-6  3  6 -8]
 [-1 -6  8 -3]]
Multiplicacion de matrices
[[ 7  4  6 40]
 [40 70  7 20]
 [ 2 27 20 10]]
Division de matrices
[[0.14285714 4.         0.66666667 1.6       ]
 [0.4        1.42857143 7.         0.2       ]
 [0.5        0.33333333 5.         0.4       ]]


In [3]:
print ("Matriz 1")
m3 = np.random.randint(1,11,[3,4])
print (m3)
print (m3.shape)
print ("Matriz 2")
m4 = np.random.randint(1,11,[4,3])
print (m4)
print (m4.shape)

print (np.dot(m3,m4))

Matriz 1
[[10  6 10  9]
 [ 4  2  3  7]
 [ 3  6 10  9]]
(3, 4)
Matriz 2
[[ 9  9  9]
 [ 6  9  1]
 [10  4  4]
 [ 2  8  1]]
(4, 3)
[[244 256 145]
 [ 92 122  57]
 [181 193  82]]


In [4]:
print ("Matriz 1")
m5 = np.random.randint(1,11,[2,2])
print (m5.shape)
print (type (m5))
print (m5)
print (m5.T)

Matriz 1
(2, 2)
<class 'numpy.ndarray'>
[[6 7]
 [6 4]]
[[6 6]
 [7 4]]


In [5]:
print ("Matriz 1")
m6 = np.random.randint(1,11,[4,3])
m7 = np.array([1,0,2])
print (m6.shape)
print (m7.shape)
m8 = np.empty_like(m6)
print (m6)
print ("------------------------")
print (m7)
print (m8.shape)
print ("------------------------")
print (m8)

Matriz 1
(4, 3)
(3,)
[[10  9  5]
 [10  4  3]
 [ 4  4  8]
 [ 4  1  9]]
------------------------
[1 0 2]
(4, 3)
------------------------
[[4594314991293244562 4616189618054758400 4604180019048437077]
 [4609884578576439706 4600877379321698714 4609112532926033335]
 [4619567317775286272 4596373779694328218 4602678819172646912]
 [4599676419421066581 4617315517961601024 4600877379321698714]]


In [6]:
for i in range(4):
  m8[i,:]= m6[i,:]+m7
print (m6)
print (m7)
print (m8)

[[10  9  5]
 [10  4  3]
 [ 4  4  8]
 [ 4  1  9]]
[1 0 2]
[[11  9  7]
 [11  4  5]
 [ 5  4 10]
 [ 5  1 11]]


In [7]:
a = np.array([1,2,3])
print (a)
b = np.tile(a,(6,1))
print (b)
print (b.shape)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(6, 3)


In [8]:
m1 = np.random.randint(20,30,[6,6])
print (m1)

[[24 20 28 23 22 27]
 [22 29 26 24 26 28]
 [23 23 28 28 24 20]
 [26 24 29 21 29 24]
 [21 27 28 25 21 23]
 [20 26 20 23 27 28]]


In [9]:
print('Matriz A')
A = np.array([1,2,3])

print(A)

print(' ')
print('---------------------------')
print(' ')

print('Matriz B')
B = np.array([1,2,3])
matriz = np.tile(B, (6, 1))
print(matriz)

print(' ')
print('---------------------------')
print(' ')

print('Matriz C')
C = np.random.randint(0, 11, size=(6, 6))
print(C)
promedio = np.mean(C)
print(' ')
print('Promedio')
print(promedio)

print(' ')
print('---------------------------')
print(' ')

promedio1 = np.mean(C, axis=1)
print(' ')
print('Promedio por filas')
print(promedio1)

print(' ')
print('---------------------------')
print(' ')

promedio2 = np.mean(C, axis=0)
print(' ')
print('Promedio por columnas')
print(promedio2)

Matriz A
[1 2 3]
 
---------------------------
 
Matriz B
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
 
---------------------------
 
Matriz C
[[ 6  7  2  7  2  5]
 [ 9  2  5  3 10  3]
 [ 1  0  5  7  0  7]
 [ 2  1  1  4  5  4]
 [ 4  4  2  4  6  2]
 [10  3  1  5  0  5]]
 
Promedio
4.0
 
---------------------------
 
 
Promedio por filas
[4.83333333 5.33333333 3.33333333 2.83333333 3.66666667 4.        ]
 
---------------------------
 
 
Promedio por columnas
[5.33333333 2.83333333 2.66666667 5.         3.83333333 4.33333333]
