<a href="https://colab.research.google.com/github/Melany1523/IAWorks/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis
By Melany Molina M.

In [34]:
# Import numpy as np and see the version
# your code here
import numpy as np
print (np.__version__)

1.23.5


In [35]:
# Create a 1D array of numbers from 0 to 9
# your code here
a = np.arange(10)
print (a)
print (a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [36]:
# Create random vector of size 10 and replace the maximum value by 0
b = np.random.randint(1,11,[10])
print (b)
maxnum = np.argmax(b)
b[maxnum] = 0
print (b)
print (b.shape)

[ 2  1 10  9  7 10  4  8  6  3]
[ 2  1  0  9  7 10  4  8  6  3]
(10,)


In [37]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print (arr[1,2])

8


In [38]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print (arr[2:5])

[3 4 5]


In [39]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print (arr[3:9])

[4 5 6 7]


In [40]:
# Create a 3×3 numpy array of all True’s
# your code here
arr = np.ones((3,3), dtype=bool)
print (arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# Extract all odd numbers from arr
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[ True  True  True  True  True  True  True  True  True]


In [58]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [60]:
# Reverse a vector (first element becomes last)
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [61]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
random_10x10 = np.random.randint(0, 100, (10, 10))
print(random_10x10)
print("Minimum value:", np.min(random_10x10))
print("Maximum value:", np.max(random_10x10))

[[15 14 48 57 68 91  6 54 70 90]
 [48 74 32 58  9 22 94 57 71 89]
 [85 50 99 82 18 21 55 30 39 89]
 [94 86 49 80 85 41 33 87 94 95]
 [86 61  2 20 99 19 79 58 54 15]
 [58 16 69 68 72 74 10  6 59 93]
 [67  6 88 55 85 81 35 36 19 29]
 [25 79 47 51 61 53 25 34 28 19]
 [41 11  3 76 13 63  9 25  4 40]
 [18 15 91  0 24 51 99 58 70 90]]
Minimum value: 0
Maximum value: 99


In [62]:
# Create a 3x3x3 array with random values
random3 = np.random.random((3, 3, 3))
print(random3)

[[[0.08408909 0.76917162 0.30805558]
  [0.05147049 0.956422   0.06018149]
  [0.25737157 0.01583493 0.38655452]]

 [[0.25924847 0.26273561 0.38802761]
  [0.85603504 0.74494353 0.88177295]
  [0.5683527  0.69545464 0.70243661]]

 [[0.34373841 0.61155443 0.94998466]
  [0.39599357 0.48140622 0.69880923]
  [0.17338228 0.08520235 0.23320932]]]


In [63]:
# Replace all odd numbers in arr with -1
# your code here
arr[arr % 2 != 0] = -1
print(arr)

[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]


In [64]:
# Create an array of type float
float_arr = np.array([1.0, 2.5, 3.7], dtype=float)
print(float_arr)

[1.  2.5 3.7]


In [65]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
arr_1d = np.arange(6)
arr_2d = arr_1d.reshape(2, -1)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [71]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0, 10, 10)
print (Z1, Z2)
common_values = np.intersect1d(Z1, Z2)
print(common_values)

[7 8 6 0 0 5 0 3 2 1] [5 5 2 3 2 5 8 0 3 8]
[0 2 3 5 8]


In [73]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print (A, B)
are_equal = np.array_equal(A, B)
print(are_equal)

[0 1 1 1 1] [0 0 0 0 1]
False


In [74]:
# Stack arrays a and b vertically
# your code here
stacked_arrays = np.vstack((A, B))
print(stacked_arrays)

[[0 1 1 1 1]
 [0 0 0 0 1]]


In [75]:
# Stack the arrays a and b horizontally.
# your code here
stacked_arrays = np.hstack((A, B))
print(stacked_arrays)

[0 1 1 1 1 0 0 0 0 1]


In [76]:
# Get all items between 5 and 10 from array tmp.
# your code here
tmp = np.array([1, 6, 11, 7, 9, 3, 14])
selected_items = tmp[(tmp >= 5) & (tmp <= 10)]
print(selected_items)

[6 7 9]


In [77]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
def pair_max(a, b):
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [78]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)


[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [79]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_decimal_5_10 = np.random.uniform(5, 10, (5, 3))
print(random_decimal_5_10)

[[8.67372436 6.43714117 9.83316742]
 [7.67703518 5.33362475 9.05493281]
 [6.46506315 7.04405049 6.67650249]
 [6.79285787 9.87902486 8.56583624]
 [6.90624701 9.60205053 8.42776961]]
